class_name CombatFeedbackData
extends Resource

@export var enemy_hit_scale: float = 1.12
@export var enemy_hit_duration: float = 0.1
@export var enemy_hit_color: Color = Color(1.0, 0.35, 0.32, 1.0)
@export var enemy_death_scale: float = 1.35
@export var enemy_death_duration: float = 0.18
@export var enemy_death_color: Color = Color(1.0, 0.72, 0.28, 1.0)
@export var damage_number_lifetime: float = 0.55
@export var damage_number_rise: float = 34.0
@export var damage_number_spread: float = 18.0
@export var damage_number_color: Color = Color(1.0, 0.82, 0.32, 1.0)
@export var damage_number_elite_color: Color = Color(1.0, 0.48, 0.18, 1.0)
@export var damage_number_boss_color: Color = Color(1.0, 0.22, 0.92, 1.0)
@export var player_hit_flash_color: Color = Color(1.0, 0.94, 0.72, 1.0)
@export var player_hit_flash_duration: float = 0.12
@export var xp_drop_scatter_radius: float = 28.0
@export var xp_drop_scatter_duration: float = 0.18
@export var camera_shake_strength: float = 4.0
@export var camera_shake_duration: float = 0.12
@export var camera_shake_min_interval: float = 0.08
@export var explosion_effect_duration: float = 0.18
@export var explosion_effect_ring_width: float = 5.0
@export var explosion_effect_ring_color: Color = Color(1.0, 0.56, 0.18, 0.9)
@export var explosion_effect_fill_color: Color = Color(1.0, 0.32, 0.12, 0.18)
@export var pressure_warning_duration: float = 0.45
@export var pressure_warning_ring_width: float = 4.0
@export var pressure_warning_ring_color: Color = Color(1.0, 0.12, 0.08, 0.95)
@export var pressure_warning_fill_color: Color = Color(1.0, 0.06, 0.03, 0.18)
@export var pressure_warning_marker_size: float = 14.0
@export var pressure_warning_marker_width: float = 3.0
@export var pressure_warning_marker_color: Color = Color(1.0, 0.92, 0.72, 0.95)
@export var pressure_warning_countdown_width: float = 7.0
@export var pressure_warning_countdown_color: Color = Color(1.0, 0.88, 0.28, 0.95)
@export var pressure_warning_edge_marker_count: int = 4
@export var pressure_warning_edge_marker_size: float = 9.0
@export var pressure_warning_edge_marker_color: Color = Color(1.0, 0.2, 0.12, 0.9)
@export var pressure_impact_duration: float = 0.16
@export var pressure_impact_ring_width: float = 6.0
@export var pressure_impact_ring_color: Color = Color(1.0, 0.78, 0.28, 0.95)
@export var pressure_impact_fill_color: Color = Color(1.0, 0.36, 0.08, 0.24)
@export var pressure_impact_burst_count: int = 10
@export var pressure_impact_burst_length: float = 16.0
@export var pressure_impact_burst_width: float = 3.0
@export var pressure_impact_burst_color: Color = Color(1.0, 0.94, 0.48, 0.95)
