class_name MapTileLayoutData
extends Resource

@export var tile_world_size: Vector2 = Vector2(256.0, 256.0)
@export var base_tile_texture_size: Vector2i = Vector2i(128, 128)
@export var base_source_cell_size: Vector2i = Vector2i.ZERO
@export var tile_edge_overlap: float = 0.0
@export var base_tile_draw_scale: float = 1.0
@export var base_tile_alpha_bleed: bool = false
@export_range(0, 64, 1) var base_tile_alpha_bleed_iterations: int = 16
@export var base_dual_grid_enabled: bool = false
@export var base_dual_grid_offset_factor: Vector2 = Vector2(0.5, 0.5)
@export_range(0.0, 1.0, 0.01) var base_dual_grid_alpha: float = 0.45
@export var base_alpha: float = 0.86
@export var draw_background_texture: bool = false
@export var background_world_margin: Vector2 = Vector2.ZERO
@export var draw_ground_base_color: bool = true
@export var draw_base_tiles: bool = true
@export var use_curated_arena_layout: bool = false
@export var arena_center_tile_indices: Array[int] = []
@export var arena_lane_tile_indices: Array[int] = []
@export var arena_ring_tile_indices: Array[int] = []
@export var arena_rubble_tile_indices: Array[int] = []
@export var draw_procedural_grid: bool = true
@export var draw_procedural_panel_lines: bool = true
@export var draw_procedural_cracks: bool = true
@export var draw_procedural_neon_lines: bool = true
@export var ground_detail_spacing: Vector2i = Vector2i(4, 3)
@export var ground_detail_phase: Vector2i = Vector2i(1, 1)
@export var ground_detail_alpha: float = 0.58
@export var decal_spacing: Vector2i = Vector2i(5, 4)
@export var decal_phase: Vector2i = Vector2i(2, 2)
@export var decal_alpha: float = 0.52
@export var neon_spacing: Vector2i = Vector2i(7, 5)
@export var neon_phase: Vector2i = Vector2i(3, 2)
@export var neon_alpha: float = 0.76
@export var draw_hazard_textures: bool = true
@export var hazard_texture_alpha: float = 0.82
@export var hazard_fill_alpha: float = 0.0
@export var random_prop_count: int = 90
@export var random_obstacle_count: int = 22
@export var random_prop_min_distance_from_origin: float = 520.0
@export var random_obstacle_min_distance_from_origin: float = 720.0
@export var random_obstacle_min_spacing: float = 280.0
@export var random_seed: int = 1827
@export var prop_scale_range: Vector2 = Vector2(0.55, 0.95)
@export var obstacle_scale_range: Vector2 = Vector2(0.72, 1.18)
@export var prop_visual_scale_multiplier: float = 1.0
@export var obstacle_visual_scale_multiplier: float = 1.0
@export var prop_tint: Color = Color.WHITE
@export var obstacle_tint: Color = Color.WHITE
@export var obstacle_collision_scale: float = 0.46
@export var obstacle_collision_footprint_scale: Vector2 = Vector2(1.0, 1.0)
@export var obstacle_collision_footprint_offset: Vector2 = Vector2.ZERO
